# Model arguments
model_name_or_path: cognitivecomputations/dolphin-2.9.4-llama3.1-8b
torch_dtype: null

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  data/fr_iter0: 1.0
  data/de_iter0: 1.0
  data/es_iter0: 1.0
  data/en_iter0: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: true
eval_strategy: steps
eval_steps: 6000
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: model/datagen_multi_iter0
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
save_strategy: "steps"
save_steps: 3000
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
rpo_alpha: 0.4